name: iCount

#shamelessy stolen from iCount github - going to try installing iCount by pip through env file as small change...
#

channels:
  - bioconda
  - conda-forge

dependencies:
  - snakemake=5.5.4
  - python=3.6
  - jinja2=2.10.1
  - networkx=2.3
  - bcftools=1.9
  - samtools=1.9
  - bwa=0.7.17
  - pysam=0.14
  - cutadapt=2.4
  - bedtools=2.28
  - STAR=2.7.2a
  - trim-galore=0.6.4
  - pip=19.2.3
  - pybedtools=0.8.0
  - numpy=1.17.1
  - pandas=0.25.1
  - pybedtools=0.8.0
  - numpydoc=0.9.1
  - sphinx=2.2.0
  - matplotlib=3.1.0
  - docutils=0.15.2
  - sphinx_rtd_theme=0.4.3
  - sphinx-releases=1.6.1

  #- pip:
  #  - iCount
