
#path to directory where xlink bed files you would like to merge are stored
#all files ending with .bed in this directory will be passed to iCount group
xlink_beds_input_dir: input_beds/

output_directory: output/

#prefix for name of combined BED files
#e.g. will output {combined_prefix}.xl_sites.bed, {combined_prefix}.peaks.bed etc.
combined_prefix: tdp43_combined_mm10

#parsed into internal structure by iCount segment
gtf_annotation: /path/to/gtf

#Required for iCount segment
genome_index_fai: /path/to/genome/fasta/index

#Parameters for iCount peaks

peaks_fdr_threshold: 0.05

peaks_n_permutations: 100

peaks_half_window: 3

peaks_group_by: gene_id
